export const labels = {
  header: "Contact Me",
  nameLabel: "Name",
  emailLabel: "Email",
  subjectLabel: "Subject",
  messageLabel: "Message",
  namePlaceholder: "John Doe",
  emailPlaceholder: "jdoe@acme.com",
  subjectPlaceholder: "Hey Sunny!",
  messagePlaceholder: "I wanted to discuss something...",
  cancelBtnText: "Cancel",
  submitBtnText: "Submit",
  submitMessage: "Message Sent Successfully",
  closeWindow: "Close Window",
}
