# Netlify CMS Configuration File
# When running in development
# set the backend name to 'test-repo'
# otherwise it should be set
# to 'git-gateway' when running
# in production

backend:
  name: test-repo
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: site-data
    label: "Site Data"
    files:
      - file: "static/cms/site-data/bio.json"
        name: bio
        label: "Bio"
        fields:
          - label: "Bio"
            name: "bio"
            widget: "text"

      - file: "static/cms/site-data/contact.json"
        name: contact-info
        label: "Contact Info"
        fields:
          - label: "Email"
            name: "email"
            widget: "string"

          - label: "Phone Number"
            name: "phone-number"
            widget: "string"

          - label: "Alternate Phone Number"
            name: "phone-number-alt"
            widget: "string"

          - label: "Instagram"
            name: "instagram"
            widget: "string"

          - label: "Twitter"
            name: "twitter"
            widget: "string"

          - label: "Github"
            name: "github"
            widget: "string"

          - label: "LinkedIn"
            name: "linkedin"
            widget: "string"

          - label: "The Practical Dev"
            name: "dev-to"
            widget: "string"

      - file: "static/cms/site-data/work.json"
        name: "work"
        label: "Work Data"
        fields:
          - label: "Previous Work"
            name: "work-data"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"

              - label: "URL"
                name: "url"
                widget: "string"

              - label: "Description"
                name: "description"
                widget: "text"

              - label: Project Type
                name: project-type
                widget: select
                options:
                  - label: Side Project
                    value: side-project

                  - label: Professional Project
                    value: professional

              - label: Show in Projects
                name: show-in-projects
                widget: boolean

  - name: resume-data
    label: "Resume Data"
    files:
      - file: "static/cms/resume-data/contact-info.json"
        name: contact-info
        label: "Contact Info"
        fields:
          - label: "Phone Number"
            name: phone
            widget: string

          - label: "Email Address"
            name: email
            widget: string

          - label: "Website"
            name: website
            widget: string

          - label: "LinkedIn"
            name: linkedin
            widget: string

          - label: "Github"
            name: github
            widget: string

      - file: "static/cms/resume-data/education.json"
        name: education
        label: "Education Info"
        fields:
          - label: "Education"
            name: education
            widget: list
            fields:
              - label: "College Name"
                name: college-name
                widget: string

              - label: "Degree Earned"
                name: degree-earned
                widget: string

              - label: "Graduation Date"
                name: grad-date
                widget: string

      - file: "static/cms/resume-data/side-projects.json"
        name: side-projects
        label: "Side Projects Info"
        fields:
          - label: "Side Projects"
            name: side-projects
            widget: list
            fields:
              - label: "Name"
                name: name
                widget: string

              - label: "Start Date"
                name: start-date
                widget: datetime

              - label: "End Date"
                name: end-date
                widget: datetime

              - label: "Description"
                name: description
                widget: text

              - label: "Link"
                name: link
                widget: string

              - label: "Type"
                name: type
                widget: string
