collections:
  - name: resume-data
    label: "Resume Data"
    files:
      - file: "public/cms/resume-data/education.json"
        name: education
        label: "Education"
        fields:
          - label: "Education"
            name: education
            widget: list
            fields:
              - label: "College Name"
                name: college-name
                widget: string

              - label: "Degree Earned"
                name: degree-earned
                widget: string

              - label: "Graduation Date"
                name: grad-date
                widget: date
                format: "MMM YYYY"

      - file: "public/cms/resume-data/side-projects.json"
        name: side-projects
        label: "Side Projects"
        fields:
          - label: "Side Projects"
            name: side-projects
            widget: list
            fields:
              - label: "Name"
                name: name
                widget: string

              - label: "Start Date"
                name: start-date
                widget: date
                format: "MMM YYYY"

              - label: "Current Project"
                name: current-project
                widget: boolean
                required: false
                default: false

              - label: "End Date"
                name: end-date
                widget: date
                format: "MMM YYYY"
                required: false

              - label: "Description"
                name: description
                widget: text
                required: false

              - label: "Link"
                name: link
                widget: string
                required: false

              - label: "Type"
                name: type
                widget: string

      - file: "public/cms/resume-data/skills.json"
        name: skills
        label: "Skills"
        fields:
          - label: "Skills"
            name: skills
            widget: list
            fields:
              - label: "Skill Description"
                name: skill
                widget: text

      - file: "public/cms/resume-data/work-experience.json"
        name: work
        label: "Work Experience"
        fields:
          - label: "Work Experience"
            name: work-experience
            widget: list
            fields:
              - label: "Name"
                name: name
                widget: string

              - label: "Position"
                name: position
                widget: string

              - label: "Start Date"
                name: start-date
                widget: date
                format: "MMM YYYY"

              - label: "End Date"
                name: end-date
                widget: date
                format: "MMM YYYY"
                required: false

              - label: Current Employer
                name: current-employer
                widget: boolean
                default: false
                required: false

              - label: "URL"
                name: url
                widget: string
                required: false

              - label: "Accomplishments"
                name: accomplishments
                widget: list
                required: false
                fields:
                  - label: "Accomplishment"
                    name: accomplishment
                    widget: text
