# This CI's sole job is to try and build the website when
# Anything is pushed to production. And report back the current
# Build status

name: Test Build CI

on:
  push:
    branches:
      - master
      - dev-2022

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.1"

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Test Build Site
        run: yarn dry-build
