# This workflow runs on the master branch whenever anything is merged in
# This workflow ensures that the production version of the site is always
# Building properly
name: Production Tests CI

on:
  push:
    branches:
      - master

jobs:
  production-tests:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run Prettier Tests
        run: yarn format

      - name: Run Lint Tests
        run: yarn lint

      - name: Run Typechecking
        run: yarn tsc

      - name: Lint CMS Config
        run: yarn cms:lint
