name: Pull Request CI

on:
  pull_request:
    branches:
      - master
      - dev-2022

jobs:
  pr-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [14.x]

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Typechecking
        run: yarn typecheck

      - name: Run Prettier
        run: yarn format

      - name: Run ESLint
        run: yarn lint

      - name: Lint CMS Config
        run: yarn cms:lint

      - name: Run Dry Build
        run: yarn dry-build
