name: Pull Request CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pr-tests:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Typechecking
        run: yarn tsc

      - name: Run Prettier
        run: yarn format

      - name: Run ESLint
        run: yarn lint
